sudo: false
language: ruby
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1.10
  - 2.0.0
  - jruby-9.1.9.0
before_install:
  - gem install bundler -v 1.15.4
  - npm install -g nyc
before_script:
  - rake dev:install
matrix:
  allow_failures:
  - rvm: jruby-9.1.9.0
