sudo: false
language: ruby
rvm:
  #- ruby-head
  #- 2.5.0
  #- 2.4.1
  #- 2.3.4
  #- 2.2.7
  #- 2.1.10
  #- jruby-head
  #- jruby-9.1.9.0
  - truffleruby

install:
  - gem install bundler
  # Necessary for truffleruby to handle nokogiri
  - if [ $TRAVIS_RUBY_VERSION = "truffleruby" ]; then echo We are on truffleruby; bundle config build.nokogiri --use-system-libraries; fi
  - rake dev:install
  - npm install -g nyc
script:
  - bundle exec rake test:all
matrix:
  allow_failures:
  include:
    - rmv: truffleruby
